/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AdditionalISSN {
    /**
    * The actual ISSN value
    */
    'issn': string;
    'typeDiscriminator': string;

    static readonly discriminator: string | undefined = "typeDiscriminator";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "issn",
            "baseName": "issn",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeDiscriminator",
            "baseName": "typeDiscriminator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AdditionalISSN.attributeTypeMap;
    }
    
    public constructor() {
        this.typeDiscriminator = "AdditionalISSN";
    }
}

