/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { HttpFile } from '../http/http';

/**
* A physical address
*/
export class Address {
    /**
    * Name of road and house number, eg. 'Pennsylvania Avenue' or '123 Main St.'
    */
    'road'?: string;
    /**
    * Room number or name if available, eg. '1.23' or 'Office of Creative Services'
    */
    'room'?: string;
    /**
    * Building Name if available, eg. 'Couper Administration Building'
    */
    'building'?: string;
    /**
    * Postal code
    */
    'postalCode'?: string;
    /**
    * City or town, eg. 'Binghamton'
    */
    'city'?: string;
    'country'?: ClassificationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "road",
            "baseName": "road",
            "type": "string",
            "format": ""
        },
        {
            "name": "room",
            "baseName": "room",
            "type": "string",
            "format": ""
        },
        {
            "name": "building",
            "baseName": "building",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "ClassificationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Address.attributeTypeMap;
    }
    
    public constructor() {
    }
}

