/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalISSN } from './AdditionalISSN';
import { HttpFile } from '../http/http';

/**
* Additional non electronic ISSN, is searchable but cannot be used when relating the journal to other content
*/
export class AlternativeISSN extends AdditionalISSN {

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AlternativeISSN.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "AlternativeISSN";
    }
}

