/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { HttpFile } from '../http/http';

/**
* Holds information on the article processing charge
*/
export class ArticleProcessingCharge {
    /**
    * This value is true if the processing charge has been paid, false if not and null/not presentif unknown or not noted on content.
    */
    'paid'?: boolean;
    /**
    * A real number denoting the amount paid in the selected currency.
    */
    'amountInCurrency'?: number;
    'currency'?: ClassificationRef;
    /**
    * A real number denoting the amount paid in the system currency.
    */
    'amount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paid",
            "baseName": "paid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "amountInCurrency",
            "baseName": "amountInCurrency",
            "type": "number",
            "format": "double"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return ArticleProcessingCharge.attributeTypeMap;
    }
    
    public constructor() {
    }
}

