/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ClassifiedIdAllOf } from './ClassifiedIdAllOf';
import { Identifier } from './Identifier';
import { HttpFile } from '../http/http';

/**
* A classified ID
*/
export class ClassifiedId extends Identifier {
    /**
    * Pure database ID of the object
    */
    'pureId'?: number;
    /**
    * Classified ID
    */
    'id': string;
    'type'?: ClassificationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ClassificationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ClassifiedId.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "ClassifiedId";
    }
}

