/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { GeoLocation } from './GeoLocation';
import { HttpFile } from '../http/http';

/**
* A physical address
*/
export class ClassifiedAddress {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'addressType'?: ClassificationRef;
    /**
    * Address for personal residence
    */
    'addressLines'?: string;
    /**
    * The name of the street
    */
    'street'?: string;
    /**
    * The name of the building
    */
    'building'?: string;
    /**
    * The postal code of the city
    */
    'postalcode'?: string;
    /**
    * The name of the city
    */
    'city'?: string;
    'country'?: ClassificationRef;
    'subdivision'?: ClassificationRef;
    'geoLocation'?: GeoLocation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "addressType",
            "baseName": "addressType",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "addressLines",
            "baseName": "addressLines",
            "type": "string",
            "format": ""
        },
        {
            "name": "street",
            "baseName": "street",
            "type": "string",
            "format": ""
        },
        {
            "name": "building",
            "baseName": "building",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalcode",
            "baseName": "postalcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "subdivision",
            "baseName": "subdivision",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "geoLocation",
            "baseName": "geoLocation",
            "type": "GeoLocation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClassifiedAddress.attributeTypeMap;
    }
    
    public constructor() {
    }
}

