/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ClassificationsKeywordGroupAllOf } from './ClassificationsKeywordGroupAllOf';
import { KeywordGroup } from './KeywordGroup';
import { HttpFile } from '../http/http';

/**
* De-normalized version of the full keyword group representation for instances where only structured keywords can be selected
*/
export class ClassificationsKeywordGroup extends KeywordGroup {
    /**
    * A list classifications extracted from the keyword group structured keyword concept
    */
    'classifications'?: Array<ClassificationRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "classifications",
            "baseName": "classifications",
            "type": "Array<ClassificationRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ClassificationsKeywordGroup.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "ClassificationsKeywordGroup";
    }
}

