/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationSchemeRefAllOf } from './ClassificationSchemeRefAllOf';
import { ContentRef } from './ContentRef';
import { NavigationLink } from './NavigationLink';
import { HttpFile } from '../http/http';

/**
* A reference to a classification scheme
*/
export class ClassificationSchemeRef extends ContentRef {
    /**
    * Classification scheme base URI
    */
    'baseUri': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseUri",
            "baseName": "baseUri",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ClassificationSchemeRef.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.systemName = "ClassificationSchemeRef";
    }
}

