/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompoundDate } from './CompoundDate';
import { HttpFile } from '../http/http';

/**
* A date range of that can be defined by only year, year and month or a full date
*/
export class CompoundDateRange {
    'startDate'?: CompoundDate;
    'endDate'?: CompoundDate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "CompoundDate",
            "format": ""
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "CompoundDate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CompoundDateRange.attributeTypeMap;
    }
    
    public constructor() {
    }
}

