/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventRef } from './EventRef';
import { HttpFile } from '../http/http';

export class ContributionToConferenceAllOf {
    /**
    * The pages of the host publication covered by this contribution, for example 10-15.
    */
    'pages'?: string;
    /**
    * The number of pages in the research output.
    */
    'numberOfPages'?: number;
    'event'?: EventRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pages",
            "baseName": "pages",
            "type": "string",
            "format": ""
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "EventRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContributionToConferenceAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

