/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalFileElectronicVersion } from './AdditionalFileElectronicVersion';
import { ArticleProcessingCharge } from './ArticleProcessingCharge';
import { BookSeriesJournalAssociation } from './BookSeriesJournalAssociation';
import { CaseNote } from './CaseNote';
import { ClassificationRef } from './ClassificationRef';
import { ClassifiedLocalizedValue } from './ClassifiedLocalizedValue';
import { ConferenceSeriesRef } from './ConferenceSeriesRef';
import { ContributionToBookAnthologyAllOf } from './ContributionToBookAnthologyAllOf';
import { ContributorAssociation } from './ContributorAssociation';
import { ElectronicVersion } from './ElectronicVersion';
import { EventRef } from './EventRef';
import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { FormattedString } from './FormattedString';
import { Identifier } from './Identifier';
import { KeywordGroup } from './KeywordGroup';
import { Link } from './Link';
import { Name } from './Name';
import { OrganizationRef } from './OrganizationRef';
import { PublicationSeries } from './PublicationSeries';
import { PublicationStatus } from './PublicationStatus';
import { PublisherRef } from './PublisherRef';
import { ResearchOutput } from './ResearchOutput';
import { Visibility } from './Visibility';
import { Workflow } from './Workflow';
import { HttpFile } from '../http/http';

/**
* Books, reports and anthologies/collected works where the author(s) are only responsible for part of the work, e.g. a chapter.
*/
export class ContributionToBookAnthology extends ResearchOutput {
    /**
    * The place of publication.
    */
    'placeOfPublication'?: string;
    /**
    * The edition that the production was published in.
    */
    'edition'?: string;
    /**
    * The ISBN number for the printed versions of the production.
    */
    'printISBNs'?: Array<string>;
    /**
    * The ISBN number for the electronic versions of the production.
    */
    'electronicISBNs'?: Array<string>;
    'publisher'?: PublisherRef;
    'event'?: EventRef;
    /**
    * The publication series this research output is part of.
    */
    'publicationSeries'?: Array<PublicationSeries>;
    /**
    * The pages of the host publication covered by this contribution, for example 10-15.
    */
    'pages'?: string;
    /**
    * The volume that the research output was published in.
    */
    'volume'?: string;
    /**
    * A list of host publication editors.
    */
    'hostPublicationEditors'?: Array<Name>;
    'hostPublicationTitle'?: FormattedString;
    'hostPublicationSubTitle'?: FormattedString;
    /**
    * A set of string values, one for each submission locale. Note: invalid locale values will be ignored.
    */
    'translatedHostPublicationTitle'?: { [key: string]: string; };
    /**
    * A set of string values, one for each submission locale. Note: invalid locale values will be ignored.
    */
    'translatedHostPublicationSubtitle'?: { [key: string]: string; };
    /**
    * The article number.
    */
    'articleNumber'?: string;
    /**
    * A collection of court case notes related to this research output.
    */
    'caseNotes'?: Array<CaseNote>;
    'commissioningBody'?: ExternalOrganizationRef;
    /**
    * The book series this research output is part of.
    */
    'bookSeries'?: Array<BookSeriesJournalAssociation>;
    /**
    * The chapter of the host publication covered by this contribution, for example 2.
    */
    'chapter'?: string;
    'conferenceSeries'?: ConferenceSeriesRef;
    /**
    * The number of pages in the research output.
    */
    'numberOfPages'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "placeOfPublication",
            "baseName": "placeOfPublication",
            "type": "string",
            "format": ""
        },
        {
            "name": "edition",
            "baseName": "edition",
            "type": "string",
            "format": ""
        },
        {
            "name": "printISBNs",
            "baseName": "printISBNs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "electronicISBNs",
            "baseName": "electronicISBNs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "publisher",
            "baseName": "publisher",
            "type": "PublisherRef",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "EventRef",
            "format": ""
        },
        {
            "name": "publicationSeries",
            "baseName": "publicationSeries",
            "type": "Array<PublicationSeries>",
            "format": ""
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "string",
            "format": ""
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostPublicationEditors",
            "baseName": "hostPublicationEditors",
            "type": "Array<Name>",
            "format": ""
        },
        {
            "name": "hostPublicationTitle",
            "baseName": "hostPublicationTitle",
            "type": "FormattedString",
            "format": ""
        },
        {
            "name": "hostPublicationSubTitle",
            "baseName": "hostPublicationSubTitle",
            "type": "FormattedString",
            "format": ""
        },
        {
            "name": "translatedHostPublicationTitle",
            "baseName": "translatedHostPublicationTitle",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "translatedHostPublicationSubtitle",
            "baseName": "translatedHostPublicationSubtitle",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "articleNumber",
            "baseName": "articleNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseNotes",
            "baseName": "caseNotes",
            "type": "Array<CaseNote>",
            "format": ""
        },
        {
            "name": "commissioningBody",
            "baseName": "commissioningBody",
            "type": "ExternalOrganizationRef",
            "format": ""
        },
        {
            "name": "bookSeries",
            "baseName": "bookSeries",
            "type": "Array<BookSeriesJournalAssociation>",
            "format": ""
        },
        {
            "name": "chapter",
            "baseName": "chapter",
            "type": "string",
            "format": ""
        },
        {
            "name": "conferenceSeries",
            "baseName": "conferenceSeries",
            "type": "ConferenceSeriesRef",
            "format": ""
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ContributionToBookAnthology.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "ContributionToBookAnthology";
    }
}

