/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentRef } from './ContentRef';
import { HttpFile } from '../http/http';

export class DependencyViolationProblemDetailsAllOf {
    /**
    * A list of dependant content that block deletion, may not be a complete list if the number of dependencies is very large
    */
    'dependencyViolationErrors'?: Array<ContentRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dependencyViolationErrors",
            "baseName": "dependencyViolationErrors",
            "type": "Array<ContentRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DependencyViolationProblemDetailsAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

