/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DisciplinesDisciplineScheme } from './DisciplinesDisciplineScheme';
import { HttpFile } from '../http/http';

/**
* List of discipline schemes
*/
export class DisciplinesDisciplineSchemeListResult {
    /**
    * The amount of discipline schemes
    */
    'count'?: number;
    /**
    * Discipline schemes
    */
    'items'?: Array<DisciplinesDisciplineScheme>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<DisciplinesDisciplineScheme>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DisciplinesDisciplineSchemeListResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

