/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The assigned discipline and its split percentage
*/
export class DisciplinesDisciplineAssignment {
    /**
    * The assigned discipline
    */
    'disciplineId': string;
    /**
    * The split percentages within an assigned discipline scheme must sum up to 100%
    */
    'splitPercentage': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "disciplineId",
            "baseName": "disciplineId",
            "type": "string",
            "format": ""
        },
        {
            "name": "splitPercentage",
            "baseName": "splitPercentage",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return DisciplinesDisciplineAssignment.attributeTypeMap;
    }
    
    public constructor() {
    }
}

