/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentRef } from './ContentRef';
import { DisciplinesDisciplineAssignment } from './DisciplinesDisciplineAssignment';
import { HttpFile } from '../http/http';

/**
* An association between a content and a number of discipline assignments
*/
export class DisciplinesAssociation {
    'content'?: ContentRef;
    /**
    * The discipline scheme these disciplines are assigned from
    */
    'disciplineScheme'?: string;
    /**
    * A collection of assigned disciplines
    */
    'disciplineAssignments'?: Array<DisciplinesDisciplineAssignment>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "ContentRef",
            "format": ""
        },
        {
            "name": "disciplineScheme",
            "baseName": "disciplineScheme",
            "type": "string",
            "format": ""
        },
        {
            "name": "disciplineAssignments",
            "baseName": "disciplineAssignments",
            "type": "Array<DisciplinesDisciplineAssignment>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DisciplinesAssociation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

