/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A discipline scheme
*/
export class DisciplinesDisciplineScheme {
    /**
    * The discipline scheme identifier
    */
    'disciplineScheme': string;
    /**
    * The discipline title
    */
    'title': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "disciplineScheme",
            "baseName": "disciplineScheme",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DisciplinesDisciplineScheme.attributeTypeMap;
    }
    
    public constructor() {
    }
}

