/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { DateRange } from './DateRange';
import { DoiElectronicVersionAllOf } from './DoiElectronicVersionAllOf';
import { ElectronicVersion } from './ElectronicVersion';
import { HttpFile } from '../http/http';

/**
* DOI electronic version related to a research output.
*/
export class DoiElectronicVersion extends ElectronicVersion {
    /**
    * The DOI of the electronic version.
    */
    'doi': string;
    'versionType'?: ClassificationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "doi",
            "baseName": "doi",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionType",
            "baseName": "versionType",
            "type": "ClassificationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(DoiElectronicVersion.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "DoiElectronicVersion";
    }
}

