/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { DateRange } from './DateRange';
import { HttpFile } from '../http/http';

/**
* Electronic version related to a research output.
*/
export class ElectronicVersion {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'accessType'?: ClassificationRef;
    'embargoPeriod'?: DateRange;
    'licenseType'?: ClassificationRef;
    /**
    * License defined by the user.
    */
    'userDefinedLicense'?: string;
    /**
    * Date where this document is/will be visible on the portal.
    */
    'visibleOnPortalDate'?: Date;
    /**
    * Username of creator
    */
    'creator'?: string;
    /**
    * Date and time of creation
    */
    'created'?: Date;
    'typeDiscriminator': string;

    static readonly discriminator: string | undefined = "typeDiscriminator";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "embargoPeriod",
            "baseName": "embargoPeriod",
            "type": "DateRange",
            "format": ""
        },
        {
            "name": "licenseType",
            "baseName": "licenseType",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "userDefinedLicense",
            "baseName": "userDefinedLicense",
            "type": "string",
            "format": ""
        },
        {
            "name": "visibleOnPortalDate",
            "baseName": "visibleOnPortalDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "typeDiscriminator",
            "baseName": "typeDiscriminator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ElectronicVersion.attributeTypeMap;
    }
    
    public constructor() {
        this.typeDiscriminator = "ElectronicVersion";
    }
}

