/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExternalOrganization } from './ExternalOrganization';
import { HttpFile } from '../http/http';

/**
* List of organizations external to the institution.
*/
export class ExternalOrganizationList {
    /**
    * External organizations
    */
    'items'?: Array<ExternalOrganization>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ExternalOrganization>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalOrganizationList.attributeTypeMap;
    }
    
    public constructor() {
    }
}

