/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { HttpFile } from '../http/http';

/**
* List of references to organizations external to the institution.
*/
export class ExternalOrganizationRefList {
    /**
    * External organization references
    */
    'items'?: Array<ExternalOrganizationRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ExternalOrganizationRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalOrganizationRefList.attributeTypeMap;
    }
    
    public constructor() {
    }
}

