/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { CompoundDateRange } from './CompoundDateRange';
import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { HttpFile } from '../http/http';

/**
* An appointment held in an external organizational unit
*/
export class ExternalAppointment {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'appointment'?: ClassificationRef;
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'appointmentString'?: { [key: string]: string; };
    'period'?: CompoundDateRange;
    'externalOrganization'?: ExternalOrganizationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "appointment",
            "baseName": "appointment",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "appointmentString",
            "baseName": "appointmentString",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "CompoundDateRange",
            "format": ""
        },
        {
            "name": "externalOrganization",
            "baseName": "externalOrganization",
            "type": "ExternalOrganizationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalAppointment.attributeTypeMap;
    }
    
    public constructor() {
    }
}

