/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Keyword } from './Keyword';
import { HttpFile } from '../http/http';

export class FreeKeywordsKeywordGroupAllOf {
    /**
    * Free keywords
    */
    'keywords'?: Array<Keyword>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<Keyword>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FreeKeywordsKeywordGroupAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

