/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FreeKeywordsKeywordGroupAllOf } from './FreeKeywordsKeywordGroupAllOf';
import { Keyword } from './Keyword';
import { KeywordGroup } from './KeywordGroup';
import { HttpFile } from '../http/http';

/**
* De-normalized version of the full keyword group representation for instances where only free keywords can be selected
*/
export class FreeKeywordsKeywordGroup extends KeywordGroup {
    /**
    * Free keywords
    */
    'keywords'?: Array<Keyword>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<Keyword>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(FreeKeywordsKeywordGroup.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "FreeKeywordsKeywordGroup";
    }
}

