/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeywordContainer } from './KeywordContainer';
import { HttpFile } from '../http/http';

export class FullKeywordGroupAllOf {
    /**
    * Containers with structured keywords and/or free keywords
    */
    'keywordContainers'?: Array<KeywordContainer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keywordContainers",
            "baseName": "keywordContainers",
            "type": "Array<KeywordContainer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FullKeywordGroupAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

