/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FullKeywordGroupAllOf } from './FullKeywordGroupAllOf';
import { KeywordContainer } from './KeywordContainer';
import { KeywordGroup } from './KeywordGroup';
import { HttpFile } from '../http/http';

/**
* Keywords of a specific type. A type of keyword can be configured to solely support free keywords (represented as the FreeKeywordsKeywordGroup type), to solely support structured keywords (represented as the ClassificationsKeywordGroup type), or to both support structured keywords supplemented by optional free keywords (this type)
*/
export class FullKeywordGroup extends KeywordGroup {
    /**
    * Containers with structured keywords and/or free keywords
    */
    'keywordContainers'?: Array<KeywordContainer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keywordContainers",
            "baseName": "keywordContainers",
            "type": "Array<KeywordContainer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(FullKeywordGroup.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "FullKeywordGroup";
    }
}

