/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProblemDetails } from './ProblemDetails';
import { HttpFile } from '../http/http';

/**
* Problem details for generic failures
*/
export class GenericProblemDetails extends ProblemDetails {

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GenericProblemDetails.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.type = "GenericProblemDetails";
    }
}

