/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Geographical location
*/
export class GeoLocation {
    /**
    * Location expressed as a point
    */
    'point'?: string;
    /**
    * Location expressed as a polygon
    */
    'polygon'?: string;
    /**
    * Used to determine whether or not we may update the point. An end-user has not entered a point manually if the value of the calculated point is the same as point
    */
    'calculatedPoint'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "point",
            "baseName": "point",
            "type": "string",
            "format": ""
        },
        {
            "name": "polygon",
            "baseName": "polygon",
            "type": "string",
            "format": ""
        },
        {
            "name": "calculatedPoint",
            "baseName": "calculatedPoint",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeoLocation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

