/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivityRef } from './ActivityRef';
import { ApplicationRef } from './ApplicationRef';
import { AwardRef } from './AwardRef';
import { ResearchOutputRef } from './ResearchOutputRef';
import { HttpFile } from '../http/http';

/**
* A person's highlighted content
*/
export class HighlightedContent {
    /**
    * References to highlighted research outputs.
    */
    'researchOutputs'?: Array<ResearchOutputRef>;
    /**
    * References to highlighted activities.
    */
    'activities'?: Array<ActivityRef>;
    /**
    * References to highlighted applications.
    */
    'applications'?: Array<ApplicationRef>;
    /**
    * References to highlighted awards.
    */
    'awards'?: Array<AwardRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "researchOutputs",
            "baseName": "researchOutputs",
            "type": "Array<ResearchOutputRef>",
            "format": ""
        },
        {
            "name": "activities",
            "baseName": "activities",
            "type": "Array<ActivityRef>",
            "format": ""
        },
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<ApplicationRef>",
            "format": ""
        },
        {
            "name": "awards",
            "baseName": "awards",
            "type": "Array<AwardRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HighlightedContent.attributeTypeMap;
    }
    
    public constructor() {
    }
}

