/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalISSN } from './AdditionalISSN';
import { ClassificationRef } from './ClassificationRef';
import { ISSN } from './ISSN';
import { Identifier } from './Identifier';
import { JournalTitle } from './JournalTitle';
import { KeywordGroup } from './KeywordGroup';
import { Link } from './Link';
import { PublisherRef } from './PublisherRef';
import { Workflow } from './Workflow';
import { HttpFile } from '../http/http';

/**
* A periodical presenting articles on a particular subject.
*/
export class Journal {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    /**
    * UUID, this is the primary identity of the entity
    */
    'uuid'?: string;
    /**
    * Username of creator
    */
    'createdBy'?: string;
    /**
    * Date and time of creation
    */
    'createdDate'?: Date;
    /**
    * Username of the user that performed a modification
    */
    'modifiedBy'?: string;
    /**
    * Date and time of last modification
    */
    'modifiedDate'?: Date;
    /**
    * URL of the content on the Pure Portal
    */
    'portalUrl'?: string;
    /**
    * All pretty URLs
    */
    'prettyUrlIdentifiers'?: Array<string>;
    /**
    * UUIDs of other content items which have been merged into this content item (or similar)
    */
    'previousUuids'?: Array<string>;
    /**
    * Signals that the information is maintained by synchronization from an external system
    */
    'externallyManaged'?: boolean;
    /**
    * A hash representing the current version of the content. For new content this is null, and for existing content the current value. The property should never be modified explicitly by a client.
    */
    'version'?: string;
    /**
    * International Standard Serial Numbers of the journal, ISSNs in this list are searchable and selectable when relating the journal to other content
    */
    'issns'?: Array<ISSN>;
    /**
    * Additional International Standard Serial Numbers of the journal, ISSNs in this list are searchable but not selectable when relating the journal to other content
    */
    'additionalSearchableIssns'?: Array<AdditionalISSN>;
    'country'?: ClassificationRef;
    /**
    * Whether the journal is present in the Directory of Open Access Journals
    */
    'indexedInDoaj'?: boolean;
    /**
    * Keywords associated with the journal
    */
    'keywordGroups'?: Array<KeywordGroup>;
    /**
    * Links to websites or other URLs associated with the journal
    */
    'links'?: Array<Link>;
    'publisher'?: PublisherRef;
    /**
    * Identifiers of the Journal, often used to identify the journal in other sources, an example could be the Scopus Id of the journal
    */
    'identifiers'?: Array<Identifier>;
    /**
    * Titles of the journal, these titles will be available for use when relating the journal to other content.
    */
    'titles'?: Array<JournalTitle>;
    /**
    * Additional searchable titles of the journal, often abbreviations that are not used to show a journal, cannot be used when relating the journal to other content.
    */
    'additionalSearchableTitles'?: Array<string>;
    'type'?: ClassificationRef;
    'workflow'?: Workflow;
    /**
    * The content system name
    */
    'systemName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "portalUrl",
            "baseName": "portalUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "prettyUrlIdentifiers",
            "baseName": "prettyUrlIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "previousUuids",
            "baseName": "previousUuids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "externallyManaged",
            "baseName": "externallyManaged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "issns",
            "baseName": "issns",
            "type": "Array<ISSN>",
            "format": ""
        },
        {
            "name": "additionalSearchableIssns",
            "baseName": "additionalSearchableIssns",
            "type": "Array<AdditionalISSN>",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "indexedInDoaj",
            "baseName": "indexedInDoaj",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "keywordGroups",
            "baseName": "keywordGroups",
            "type": "Array<KeywordGroup>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "publisher",
            "baseName": "publisher",
            "type": "PublisherRef",
            "format": ""
        },
        {
            "name": "identifiers",
            "baseName": "identifiers",
            "type": "Array<Identifier>",
            "format": ""
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<JournalTitle>",
            "format": ""
        },
        {
            "name": "additionalSearchableTitles",
            "baseName": "additionalSearchableTitles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "workflow",
            "baseName": "workflow",
            "type": "Workflow",
            "format": ""
        },
        {
            "name": "systemName",
            "baseName": "systemName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Journal.attributeTypeMap;
    }
    
    public constructor() {
    }
}

