/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Link to resource
*/
export class NavigationLink {
    /**
    * System name of the kind of link (such as 'prev', 'next' etc.)
    */
    'ref'?: string;
    /**
    * Link to the resource
    */
    'href'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ref",
            "baseName": "ref",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NavigationLink.attributeTypeMap;
    }
    
    public constructor() {
    }
}

