/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A note
*/
export class Note {
    /**
    * Date and time of when the note was created, an event occurred or similar. Can be any point in time, but <now> is normally preferred
    */
    'date'?: Date;
    /**
    * Username related to the note. Usually a username of the user creating the note. Does not have to be a username of a Pure user
    */
    'username'?: string;
    /**
    * Note text
    */
    'text': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Note.attributeTypeMap;
    }
    
    public constructor() {
    }
}

