/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { OrganizationRef } from './OrganizationRef';
import { HttpFile } from '../http/http';

/**
* A reference to an organization in the institution or an external organization
*/
export class OrganizationOrExternalOrganizationRef {
    'organizationRef'?: OrganizationRef;
    'externalOrganizationRef'?: ExternalOrganizationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "organizationRef",
            "baseName": "organizationRef",
            "type": "OrganizationRef",
            "format": ""
        },
        {
            "name": "externalOrganizationRef",
            "baseName": "externalOrganizationRef",
            "type": "ExternalOrganizationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationOrExternalOrganizationRef.attributeTypeMap;
    }
    
    public constructor() {
    }
}

