/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { DateRange } from './DateRange';
import { InternalOrExternalSupervisor } from './InternalOrExternalSupervisor';
import { HttpFile } from '../http/http';

/**
* The association data of a person and their supervisor
*/
export class PersonSupervisorAssociation {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'period'?: DateRange;
    /**
    * Percentage for which the Supervisor is responsible for the total supervision
    */
    'supervisionPercentage'?: number;
    'supervisorRole'?: ClassificationRef;
    'supervisor'?: InternalOrExternalSupervisor;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "DateRange",
            "format": ""
        },
        {
            "name": "supervisionPercentage",
            "baseName": "supervisionPercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "supervisorRole",
            "baseName": "supervisorRole",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "supervisor",
            "baseName": "supervisor",
            "type": "InternalOrExternalSupervisor",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PersonSupervisorAssociation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

