/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { DateRange } from './DateRange';
import { HttpFile } from '../http/http';

/**
* Leave of absence held by a person
*/
export class PersonClassifiedLeaveOfAbsence {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'classification'?: ClassificationRef;
    'period'?: DateRange;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "classification",
            "baseName": "classification",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "DateRange",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PersonClassifiedLeaveOfAbsence.attributeTypeMap;
    }
    
    public constructor() {
    }
}

