/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompoundDateRange } from './CompoundDateRange';
import { HttpFile } from '../http/http';

/**
* The professional qualifications held by a person
*/
export class ProfessionalQualification {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'abbreviatedQualification'?: { [key: string]: string; };
    'period'?: CompoundDateRange;
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'qualification'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "abbreviatedQualification",
            "baseName": "abbreviatedQualification",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "CompoundDateRange",
            "format": ""
        },
        {
            "name": "qualification",
            "baseName": "qualification",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfessionalQualification.attributeTypeMap;
    }
    
    public constructor() {
    }
}

