/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FormattedString } from './FormattedString';
import { HttpFile } from '../http/http';

/**
* A publication series.
*/
export class PublicationSeries {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'name'?: FormattedString;
    /**
    * The publisher of the publication series.
    */
    'publisherName'?: string;
    /**
    * The print ISSN of the publication series.
    */
    'printIssn'?: string;
    /**
    * The electronic ISSN of the publication series.
    */
    'electronicIssn'?: string;
    /**
    * The number of the publication series.
    */
    'no'?: string;
    /**
    * The volume of the publication series.
    */
    'volume'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "FormattedString",
            "format": ""
        },
        {
            "name": "publisherName",
            "baseName": "publisherName",
            "type": "string",
            "format": ""
        },
        {
            "name": "printIssn",
            "baseName": "printIssn",
            "type": "string",
            "format": ""
        },
        {
            "name": "electronicIssn",
            "baseName": "electronicIssn",
            "type": "string",
            "format": ""
        },
        {
            "name": "no",
            "baseName": "no",
            "type": "string",
            "format": ""
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicationSeries.attributeTypeMap;
    }
    
    public constructor() {
    }
}

