/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { CompoundDate } from './CompoundDate';
import { HttpFile } from '../http/http';

/**
* A representation of a point in time when the status of a publication changed, e.g. the submission date or publication date of the publication.
*/
export class PublicationStatus {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    /**
    * True when this status element is the current, false otherwise.
    */
    'current'?: boolean;
    'publicationStatus'?: ClassificationRef;
    'publicationDate'?: CompoundDate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "current",
            "baseName": "current",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "publicationStatus",
            "baseName": "publicationStatus",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "publicationDate",
            "baseName": "publicationDate",
            "type": "CompoundDate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicationStatus.attributeTypeMap;
    }
    
    public constructor() {
    }
}

