/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResearchOutputPeerReviewConfiguration } from './ResearchOutputPeerReviewConfiguration';
import { HttpFile } from '../http/http';

/**
* List of research output peer review configurations
*/
export class ResearchOutputPeerReviewConfigurationListResult {
    'researchOutputPeerReviewConfigurations'?: Array<ResearchOutputPeerReviewConfiguration>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "researchOutputPeerReviewConfigurations",
            "baseName": "researchOutputPeerReviewConfigurations",
            "type": "Array<ResearchOutputPeerReviewConfiguration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResearchOutputPeerReviewConfigurationListResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

