/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { HttpFile } from '../http/http';

/**
* A specification for a publication category and it's interrelated fields: peerReview and internationalPeerReview
*/
export class ResearchOutputPeerReviewConfigurationCombination {
    'category'?: ClassificationRef;
    /**
    * Research output peer reviewable
    */
    'peerReviewable'?: ResearchOutputPeerReviewConfigurationCombinationPeerReviewableEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "peerReviewable",
            "baseName": "peerReviewable",
            "type": "ResearchOutputPeerReviewConfigurationCombinationPeerReviewableEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResearchOutputPeerReviewConfigurationCombination.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ResearchOutputPeerReviewConfigurationCombinationPeerReviewableEnum = "NOT_PEER_REVIEWABLE" | "PEER_REVIEWABLE" | "INTERNATIONAL_PEER_REVIEWABLE" ;

