/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ResearchOutputPeerReviewConfigurationCombination } from './ResearchOutputPeerReviewConfigurationCombination';
import { HttpFile } from '../http/http';

/**
* A specification for a research output type and the allowed combinations of it's interrelated fields: category, peerReview, and internationPeerReview
*/
export class ResearchOutputPeerReviewConfiguration {
    'researchOutputType'?: ClassificationRef;
    /**
    * The valid combinations of the interrelated fields
    */
    'allowedCombinations'?: Array<ResearchOutputPeerReviewConfigurationCombination>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "researchOutputType",
            "baseName": "researchOutputType",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "allowedCombinations",
            "baseName": "allowedCombinations",
            "type": "Array<ResearchOutputPeerReviewConfigurationCombination>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResearchOutputPeerReviewConfiguration.attributeTypeMap;
    }
    
    public constructor() {
    }
}

