/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ClassifiedAddress } from './ClassifiedAddress';
import { ClassifiedLocalizedValue } from './ClassifiedLocalizedValue';
import { ClassifiedValue } from './ClassifiedValue';
import { DateRange } from './DateRange';
import { KeywordGroup } from './KeywordGroup';
import { OrganizationRef } from './OrganizationRef';
import { PersonOrganizationAssociation } from './PersonOrganizationAssociation';
import { PersonSupervisorAssociation } from './PersonSupervisorAssociation';
import { StaffOrganizationAssociationAllOf } from './StaffOrganizationAssociationAllOf';
import { HttpFile } from '../http/http';

/**
* A relation describing the association between Staff and organisation
*/
export class StaffOrganizationAssociation extends PersonOrganizationAssociation {
    'contractType'?: ClassificationRef;
    /**
    * The FTE (Full-Time Equivalent). A decimal number ranging between 0 (0% equivalent of full time) and 1 (100% equivalent of full time).
    */
    'fte'?: number;
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'jobDescription'?: { [key: string]: string; };
    'jobTitle'?: ClassificationRef;
    'staffType'?: ClassificationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractType",
            "baseName": "contractType",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "fte",
            "baseName": "fte",
            "type": "number",
            "format": "double"
        },
        {
            "name": "jobDescription",
            "baseName": "jobDescription",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "staffType",
            "baseName": "staffType",
            "type": "ClassificationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(StaffOrganizationAssociation.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "StaffOrganizationAssociation";
    }
}

