/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StudentOrganizationAssociationAllOf {
    /**
    * The date when the student received an award.
    */
    'awardDate'?: Date;
    /**
    * Description of what award the student gained.
    */
    'awardGained'?: string;
    /**
    * The FTE (Full-Time Equivalent). A decimal number ranging between 0 (0% equivalent of full time) and 1 (100% equivalent of full time).
    */
    'fte'?: number;
    /**
    * The name or title of a program often consists of the degree (e.g., BS) and the discipline or field of study (e.g., Business Administration).
    */
    'programme'?: string;
    /**
    * A set of string values, one for each submission locale. Note: invalid locale values will be ignored.
    */
    'projectTitle'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "awardDate",
            "baseName": "awardDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "awardGained",
            "baseName": "awardGained",
            "type": "string",
            "format": ""
        },
        {
            "name": "fte",
            "baseName": "fte",
            "type": "number",
            "format": "double"
        },
        {
            "name": "programme",
            "baseName": "programme",
            "type": "string",
            "format": ""
        },
        {
            "name": "projectTitle",
            "baseName": "projectTitle",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudentOrganizationAssociationAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

