/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { ExternalPersonRef } from './ExternalPersonRef';
import { Name } from './Name';
import { OrganizationRef } from './OrganizationRef';
import { PersonRef } from './PersonRef';
import { HttpFile } from '../http/http';

/**
* A supervisor on a research output.
*/
export class SupervisorAssociation {
    /**
    * Pure database ID of the object, prefer using the UUID if it is present on the entity
    */
    'pureId'?: number;
    'person'?: PersonRef;
    'externalPerson'?: ExternalPersonRef;
    'name'?: Name;
    'role'?: ClassificationRef;
    /**
    * A collection of organisational unit affiliations.
    */
    'organisationalUnits'?: Array<OrganizationRef>;
    /**
    * A collection of external organisation affiliations.
    */
    'externalOrganisations'?: Array<ExternalOrganizationRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pureId",
            "baseName": "pureId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "PersonRef",
            "format": ""
        },
        {
            "name": "externalPerson",
            "baseName": "externalPerson",
            "type": "ExternalPersonRef",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "organisationalUnits",
            "baseName": "organisationalUnits",
            "type": "Array<OrganizationRef>",
            "format": ""
        },
        {
            "name": "externalOrganisations",
            "baseName": "externalOrganisations",
            "type": "Array<ExternalOrganizationRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupervisorAssociation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

