/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProblemDetails } from './ProblemDetails';
import { ValidationError } from './ValidationError';
import { ValidationProblemDetailsAllOf } from './ValidationProblemDetailsAllOf';
import { HttpFile } from '../http/http';

/**
* Problem details for validation failures
*/
export class ValidationProblemDetails extends ProblemDetails {
    'errors'?: Array<ValidationError>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ValidationError>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ValidationProblemDetails.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.type = "ValidationProblemDetails";
    }
}

