/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { HttpFile } from '../http/http';

export class VisitingScholarOrganizationAssociationAllOf {
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'jobDescription'?: { [key: string]: string; };
    'jobTitle'?: ClassificationRef;
    /**
    * Why the visiting shcolar has transfered to the organization.
    */
    'purposeOfStay'?: string;
    'visitorFrom'?: ExternalOrganizationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobDescription",
            "baseName": "jobDescription",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "purposeOfStay",
            "baseName": "purposeOfStay",
            "type": "string",
            "format": ""
        },
        {
            "name": "visitorFrom",
            "baseName": "visitorFrom",
            "type": "ExternalOrganizationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VisitingScholarOrganizationAssociationAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

