/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClassificationRef } from './ClassificationRef';
import { ClassifiedAddress } from './ClassifiedAddress';
import { ClassifiedLocalizedValue } from './ClassifiedLocalizedValue';
import { ClassifiedValue } from './ClassifiedValue';
import { DateRange } from './DateRange';
import { ExternalOrganizationRef } from './ExternalOrganizationRef';
import { KeywordGroup } from './KeywordGroup';
import { OrganizationRef } from './OrganizationRef';
import { PersonOrganizationAssociation } from './PersonOrganizationAssociation';
import { PersonSupervisorAssociation } from './PersonSupervisorAssociation';
import { VisitingScholarOrganizationAssociationAllOf } from './VisitingScholarOrganizationAssociationAllOf';
import { HttpFile } from '../http/http';

/**
* A relation describing the association between a visiting scholar and organisation
*/
export class VisitingScholarOrganizationAssociation extends PersonOrganizationAssociation {
    /**
    * A set of localized string values each for a specific submission locale. Please note that invalid locale values will be ignored.
    */
    'jobDescription'?: { [key: string]: string; };
    'jobTitle'?: ClassificationRef;
    /**
    * Why the visiting shcolar has transfered to the organization.
    */
    'purposeOfStay'?: string;
    'visitorFrom'?: ExternalOrganizationRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobDescription",
            "baseName": "jobDescription",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "ClassificationRef",
            "format": ""
        },
        {
            "name": "purposeOfStay",
            "baseName": "purposeOfStay",
            "type": "string",
            "format": ""
        },
        {
            "name": "visitorFrom",
            "baseName": "visitorFrom",
            "type": "ExternalOrganizationRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VisitingScholarOrganizationAssociation.attributeTypeMap);
    }
    
    public constructor() {
        super();
        this.typeDiscriminator = "VisitingScholarOrganizationAssociation";
    }
}

