/**
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * OpenAPI spec version: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Workflow } from './Workflow';
import { HttpFile } from '../http/http';

/**
* List of workflow steps.
*/
export class WorkflowListResult {
    /**
    * Allowed workflow steps.
    */
    'workflows'?: Array<Workflow>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workflows",
            "baseName": "workflows",
            "type": "Array<Workflow>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowListResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

